## nginx-statefulset.yaml

### Service 생성 
apiVersion: v1
kind: Service
metadata:
  name: nginx-statefulset-service
  labels:
    app: nginx-statefulset-service
spec:
  ports:
  - port: 80
    name: web
  type: ClusterIP # CluserIP
  clusterIP: None # IP=None -> Headless Service, 파드 이름을 도메인으로 사용하기 위함 
  selector:
    app: nginx-statefulset-service
---
### StatefulSet 생성
apiVersion: apps/v1
kind: StatefulSet # kind: StatefulSet
metadata:
  name: web # StatefulSet 이름
spec:
  selector:
    matchLabels:
      app: nginx-statefulset  # .spec.template.metadata.labels와 동일한 app 선택
  serviceName: "nginx-statefulset-service" # 위에서 생성한 Service 지정
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-statefulset # .spec.selector.matchLabels에서 선택되도록 Label 생성
    spec:
      terminationGracePeriodSeconds: 10 # 종료 시간 10초로 설정
      containers:
      - name: nginx-statefulset 
        image: nginx 
        ports:
        - containerPort: 80
          name: web